#!/bin/bash
#Delete a line number from a file
echo "ENTER FILENAME"
read FILENAME
if [ -f $FILENAME ]
then
    echo "FILE EXIST"
    echo "ENTER LINE NUMBER YOU WANT TO DELELTE"
    read line
lines=`wc -l $FILENAME | awk '{ print $1 }'`
if [ "$line" -gt "$lines" ]
then
    echo "LINE YOU ENTERED IS NOT AVAILABLE"
else
    sed -i "${line}d" $FILENAME 
    echo "LINE IS DELETED"
fi
else 
    echo "FILE DOES NOT EXIST"
fi

