#!/bin/bash
#Move a file from source folder to target folder.
echo "ENTER SOURCEFOLDER"
read SOURCEFOLDER
if [ -d $SOURCEFOLDER ]
then 
    echo "SOURCE FOLDER EXIST"
    echo "ENTER FILENAME"
    read FILENAME
if [ -f $SOURCEFOLDER/$FILENAME ];
then    
    echo "FILE EXIST"
    echo "enter DESTINATIONFOLDER"
    read DESTINATIONFOLDER
if [ -d $DESTINATIONFOLDER ]
then 
    mv $SOURCEFOLDER/$FILENAME $DESTINATIONFOLDER
    echo "file moved"
else
    echo "destinationfolder does not exist"
fi
else 
    echo "file does not exist"
fi
else
    echo "sourcefolder does not exist"
fi

